// Material You color tokens — teal/green tennis theme
export const C = {
  primary:             '#006B5B',
  onPrimary:           '#FFFFFF',
  primaryContainer:    '#79F8E4',
  onPrimaryContainer:  '#00201B',
  secondary:           '#4B6360',
  secondaryContainer:  '#CDE8E3',
  onSecondaryContainer:'#051F1C',
  tertiary:            '#456179',
  tertiaryContainer:   '#CCE5FF',
  surface:             '#F4FBF8',
  surfaceVariant:      '#DAE5E1',
  onSurface:           '#171D1B',
  onSurfaceVar:        '#3F4946',
  outline:             '#6F7976',
  outlineVariant:      '#BEC9C5',
  error:               '#BA1A1A',
  errorContainer:      '#FFDAD6',
  onError:             '#FFFFFF',
  scrim:               'rgba(0,0,0,0.55)',
  chipNull:            '#E8F0EE',
  chipNullText:        '#6F7976',
  chipYes:             '#C8F5D0',
  chipYesText:         '#0A3D1E',
  chipNo:              '#FFD7D5',
  chipNoText:          '#5D1313',
  winGreen:            '#1B5E20',
  losRed:              '#7F0000',
  syncGreen:           '#34A853',
} as const;
